# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
env:
  - PYTHON=""
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("GaussianRandomFields")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("GaussianRandomFields")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
